-- Steam asset manifest: one entry per image (docs/CONTEXT.md "Manifest entry").
-- Dev-only; the game never reads it. Validated by manifest_check.lua before
-- anything renders. Seeds and steps are placeholders until scout mode picks
-- real moments; glow/crt are set on every entry so output does not depend on
-- the saved in-game look.
local function ai(color, level)
	return { color = color, binding = { kind = "ai", level = level } }
end

local duel = { ai(1, "hard"), ai(2, "hard") }
local four = { ai(1, "hard"), ai(2, "hard"), ai(3, "easy"), ai(4, "easy") }
local six = { ai(1, "hard"), ai(2, "hard"), ai(3, "hard"), ai(4, "hard"), ai(5, "easy"), ai(6, "easy") }

return {
	{
		name = "screenshot_01",
		width = 1920,
		height = 1080,
		seed = 1234,
		step = 241,
		roster = four,
		glow = true,
		crt = true,
	},
	{
		name = "screenshot_02",
		width = 1920,
		height = 1080,
		seed = 4321,
		step = 354,
		roster = six,
		glow = true,
		crt = true,
	},
	{
		name = "screenshot_03",
		width = 1920,
		height = 1080,
		seed = 3131,
		step = 420,
		roster = six,
		glow = true,
		crt = true,
	},
	{
		name = "screenshot_04",
		width = 1920,
		height = 1080,
		seed = 987,
		step = 2077,
		roster = six,
		glow = true,
		crt = true,
	},
	{
		name = "screenshot_05",
		width = 1920,
		height = 1080,
		seed = 4534,
		step = 367,
		roster = six,
		glow = true,
		crt = true,
	},
	{
		name = "capsule_header",
		width = 920,
		height = 430,
		seed = 4242,
		step = 61,
		roster = four,
		hud = false,
		camera = { x = -480, y = -60, zoom = 0.95 },
		glow = true,
		crt = true,
		overlay = "logo",
		logoAnchor = "left",
		logoSize = 0.45,
		logoOffsetX = 30,
	},
	{
		name = "capsule_small",
		width = 462,
		height = 174,
		seed = 4242,
		step = 61,
		roster = four,
		hud = false,
		camera = { x = -480, y = -60, zoom = 1.18 },
		glow = true,
		crt = true,
		overlay = "logo",
		logoAnchor = "left",
		logoSize = 0.45,
		logoOffsetX = 17,
	},
	{
		name = "capsule_main",
		width = 1232,
		height = 706,
		seed = 4242,
		step = 61,
		roster = four,
		hud = false,
		camera = { x = -480, y = -60, zoom = 0.79 },
		glow = true,
		crt = true,
		overlay = "logo",
		logoAnchor = "left",
		logoSize = 0.45,
		logoOffsetX = 35,
	},
	{
		name = "capsule_vertical",
		width = 748,
		height = 896,
		seed = 4242,
		step = 61,
		roster = four,
		hud = false,
		camera = { x = 36, y = -298, zoom = 1.15 },
		glow = true,
		crt = true,
		overlay = "logo",
		logoAnchor = "top",
		logoSize = 0.9,
		logoOffsetY = 120,
	},
	{
		name = "library_capsule",
		width = 600,
		height = 900,
		seed = 4242,
		step = 61,
		roster = four,
		hud = false,
		camera = { x = 36, y = -291, zoom = 1.25 },
		glow = true,
		crt = true,
		overlay = "logo",
		logoAnchor = "top",
		logoSize = 0.9,
		logoOffsetY = 200,
	},
	{
		name = "library_header",
		width = 920,
		height = 430,
		seed = 4242,
		step = 61,
		roster = four,
		hud = false,
		camera = { x = -480, y = -60, zoom = 0.95 },
		glow = true,
		crt = true,
		overlay = "logo",
		logoAnchor = "left",
		logoSize = 0.45,
		logoOffsetX = 30,
	},
	{
		-- No overlay: Steam places the library logo over the hero itself.
		name = "library_hero",
		width = 3840,
		height = 1240,
		seed = 4242,
		step = 61,
		roster = four,
		hud = false,
		camera = { x = 36, y = -60, zoom = 1.8 },
		glow = true,
		crt = true,
	},
	{
		-- Library logo: the logo alone on a transparent canvas (max 1280x720).
		name = "logo",
		width = 1280,
		height = 360,
		seed = 4242,
		step = 0,
		roster = duel,
		glow = false,
		crt = false,
		transparent = true,
		overlay = "logo",
		logoAnchor = "centre",
		logoSize = 0.9,
	},
	{
		-- Community icon: 184x184 square with G// monogram
		name = "icon_community",
		width = 184,
		height = 184,
		seed = 4242,
		step = 0,
		roster = duel,
		glow = true,
		crt = true,
		icon = true,
	},
	{
		-- Client icon: 32x32 square with G// monogram (readability critical)
		name = "icon_client",
		width = 32,
		height = 32,
		seed = 4242,
		step = 0,
		roster = duel,
		glow = true,
		crt = true,
		icon = true,
	},
	{
		-- Master icon: 256x256 square with G// monogram
		name = "icon_master",
		width = 256,
		height = 256,
		seed = 4242,
		step = 0,
		roster = duel,
		glow = true,
		crt = true,
		icon = true,
	},
}
