local MenuNav = require("src.app.menu.menu_nav")

test("keyboard keys map to the four menu actions", function()
	assertEqual("up", MenuNav.fromKey("up"))
	assertEqual("up", MenuNav.fromKey("w"))
	assertEqual("down", MenuNav.fromKey("down"))
	assertEqual("down", MenuNav.fromKey("s"))
	assertEqual("confirm", MenuNav.fromKey("return"))
	assertEqual("confirm", MenuNav.fromKey("space"))
	assertEqual("back", MenuNav.fromKey("escape"))
	assertEqual(nil, MenuNav.fromKey("x"))
end)

test("gamepad buttons map to the same four actions", function()
	assertEqual("up", MenuNav.fromButton("dpup"))
	assertEqual("down", MenuNav.fromButton("dpdown"))
	assertEqual("confirm", MenuNav.fromButton("a"))
	assertEqual("back", MenuNav.fromButton("b"))
	assertEqual(nil, MenuNav.fromButton("x"))
end)

test("left stick up/down fires once per push, not every frame", function()
	local stick = MenuNav.newStick()
	assertEqual(nil, stick:axis("lefty", 0.2))
	assertEqual("down", stick:axis("lefty", 0.9))
	assertEqual(nil, stick:axis("lefty", 0.95))
	assertEqual(nil, stick:axis("lefty", 0))
	assertEqual("up", stick:axis("lefty", -0.9))
	assertEqual(nil, stick:axis("righty", 0.9))
end)

test("left and right map from keys, d-pad and the left stick's horizontal axis", function()
	assertEqual("left", MenuNav.fromKey("left"))
	assertEqual("left", MenuNav.fromKey("a"))
	assertEqual("right", MenuNav.fromKey("right"))
	assertEqual("right", MenuNav.fromKey("d"))
	assertEqual("left", MenuNav.fromButton("dpleft"))
	assertEqual("right", MenuNav.fromButton("dpright"))
	local stick = MenuNav.newStick()
	assertEqual("right", stick:axis("leftx", 0.9))
	assertEqual(nil, stick:axis("leftx", 0.95))
	assertEqual("left", stick:axis("leftx", -0.9))
end)

test("left/right adjust the selected item and are ignored by items that cannot", function()
	local seen = {}
	local menu = { selected = 2, items = { { action = function() end }, { action = function() end, adjust = function(dir) seen[#seen + 1] = dir end } } }
	MenuNav.apply(menu, "left")
	MenuNav.apply(menu, "right")
	assertEqual("left", seen[1])
	assertEqual("right", seen[2])
	menu.selected = 1
	MenuNav.apply(menu, "right")
	assertEqual(2, #seen)
end)

test("move wraps the selection and ignores confirm/back", function()
	assertEqual(2, MenuNav.move(1, 2, "down"))
	assertEqual(1, MenuNav.move(2, 2, "down"))
	assertEqual(2, MenuNav.move(1, 2, "up"))
	assertEqual(1, MenuNav.move(1, 2, "confirm"))
end)
