local ScoreCard = require("src.app.render.score_card")

test("result text names the winner or a draw", function()
	assertEqual("P1 WINS", ScoreCard.resultText({ winner = 1 }))
	assertEqual("P2 WINS", ScoreCard.resultText({ winner = 2 }))
	assertEqual("DRAW", ScoreCard.resultText({ draw = true }))
end)

test("pips are filled for each win and empty for the rest", function()
	local pips = ScoreCard.pips(1, 3)
	assertEqual(3, #pips)
	assertTrue(pips[1])
	assertFalse(pips[2])
	assertFalse(pips[3])
end)

test("scores list the slot with the most wins first", function()
	local order = ScoreCard.sortedSlots({ 0, 2, 1 })
	assertEqual(2, order[1])
	assertEqual(3, order[2])
	assertEqual(1, order[3])
end)

test("tied scores keep slot order", function()
	local order = ScoreCard.sortedSlots({ 1, 2, 2, 1 })
	assertEqual(2, order[1])
	assertEqual(3, order[2])
	assertEqual(1, order[3])
	assertEqual(4, order[4])
end)

test("sorting scores never changes the score table", function()
	local score = { 0, 3, 1 }
	ScoreCard.sortedSlots(score)
	assertEqual(0, score[1])
	assertEqual(3, score[2])
	assertEqual(1, score[3])
end)

test("a six-row score list fits well inside the screen height", function()
	assertTrue(ScoreCard.listHeight(6) < 400)
	assertTrue(ScoreCard.listHeight(6) > ScoreCard.listHeight(2))
end)
