local ScoreCard = require("src.app.render.score_card")

test("result text names the winner or a draw", function()
	assertEqual("P1 WINS", ScoreCard.resultText({ winner = 1 }))
	assertEqual("P2 WINS", ScoreCard.resultText({ winner = 2 }))
	assertEqual("DRAW", ScoreCard.resultText({ draw = true }))
end)

test("pips are filled for each win and empty for the rest", function()
	local pips = ScoreCard.pips(1, 3)
	assertEqual(3, #pips)
	assertTrue(pips[1])
	assertFalse(pips[2])
	assertFalse(pips[3])
end)

test("scores list the slot with the most wins first", function()
	local order = ScoreCard.sortedSlots({ 0, 2, 1 })
	assertEqual(2, order[1])
	assertEqual(3, order[2])
	assertEqual(1, order[3])
end)

test("tied scores keep slot order", function()
	local order = ScoreCard.sortedSlots({ 1, 2, 2, 1 })
	assertEqual(2, order[1])
	assertEqual(3, order[2])
	assertEqual(1, order[3])
	assertEqual(4, order[4])
end)

test("sorting scores never changes the score table", function()
	local score = { 0, 3, 1 }
	ScoreCard.sortedSlots(score)
	assertEqual(0, score[1])
	assertEqual(3, score[2])
	assertEqual(1, score[3])
end)

test("a six-row score list fits well inside the screen height", function()
	assertTrue(ScoreCard.listHeight(6) < 400)
	assertTrue(ScoreCard.listHeight(6) > ScoreCard.listHeight(2))
end)

test("the result holds centred for one second before the scores reveal", function()
	local reveal, alpha = ScoreCard.animation(0.5, 4)
	assertEqual(0, reveal)
	assertEqual(1, alpha)
	reveal = ScoreCard.animation(1, 4)
	assertEqual(0, reveal)
end)

test("the scores finish revealing and stay settled until the fade out", function()
	local reveal, alpha = ScoreCard.animation(2.5, 4)
	assertEqual(1, reveal)
	assertEqual(1, alpha)
end)

test("the card fades out over the last half second", function()
	local _, alpha = ScoreCard.animation(3.75, 4)
	assertTrue(alpha > 0 and alpha < 1)
	_, alpha = ScoreCard.animation(4, 4)
	assertEqual(0, alpha)
end)

test("the reveal rises part way through the slide", function()
	local reveal = ScoreCard.animation(1.35, 4)
	assertTrue(reveal > 0 and reveal < 1)
end)
