local Text = require("tools.trailer.text")

test("Trailer Text keeps the top anchor below the HUD's top row", function()
	local _, y = Text.place(1920, 1080, "top", 800, 60)
	assertTrue(y >= 1080 * 0.1, "y=" .. y)
end)

test("Trailer Text keeps the bottom anchor above the HUD's bottom row", function()
	local _, y = Text.place(1920, 1080, "bottom", 800, 60)
	assertTrue(y + 60 <= 1080 * 0.9, "bottom=" .. (y + 60))
end)

test("Trailer Text centres top, centre and bottom captions horizontally", function()
	local x = Text.place(1920, 1080, "bottom", 800, 60)
	assertNear(560, x, 1e-9)
end)

test("Trailer Text puts a lowerLeft caption at the safe left margin", function()
	local x = Text.place(1920, 1080, "lowerLeft", 800, 60)
	assertNear(1920 * 0.08, x, 1e-9)
end)

test("Trailer Text splits // into white, colour 1, colour 2 and white parts", function()
	local c1, c2 = { 1, 0.2, 0.2 }, { 0.2, 0.4, 1 }
	local parts = Text.parts("UP TO 6 // ONE SCREEN", { c1, c2 })
	assertEqual(4, #parts)
	assertEqual("UP TO 6 ", parts[1][1])
	assertEqual(nil, parts[1][2])
	assertEqual("/", parts[2][1])
	assertEqual(c1, parts[2][2])
	assertEqual("/", parts[3][1])
	assertEqual(c2, parts[3][2])
	assertEqual(" ONE SCREEN", parts[4][1])
	assertEqual(nil, parts[4][2])
end)

test("Trailer Text leaves text without // as one white part", function()
	local parts = Text.parts("ONE SCREEN", { { 1, 0, 0 }, { 0, 0, 1 } })
	assertEqual(1, #parts)
	assertEqual("ONE SCREEN", parts[1][1])
	assertEqual(nil, parts[1][2])
end)
