local Warp = require("tools.trailer.warp")

test("Trailer Warp outgoing blur is 0 at weight 0 and rises to max at 1", function()
	local first = Warp.outgoing(0)
	assertEqual(0, first.strength)
	assertEqual(1, first.scale)
	assertNear(Warp.MAX_STRENGTH, Warp.outgoing(1).strength, 1e-9)
	assert(Warp.outgoing(0.25).strength < Warp.outgoing(0.75).strength, "blur rises")
	assert(Warp.outgoing(1).scale > 1, "outgoing zooms outward")
end)

test("Trailer Warp incoming blur is max at weight 0 and settles to 0 at 1", function()
	assertNear(Warp.MAX_STRENGTH, Warp.incoming(0).strength, 1e-9)
	local last = Warp.incoming(1)
	assertEqual(0, last.strength)
	assertEqual(1, last.scale)
	assert(Warp.incoming(0.25).strength > Warp.incoming(0.75).strength, "blur falls")
end)

test("Trailer Warp brightness peaks at the midpoint and is 0 at the ends", function()
	assertEqual(0, Warp.brightness(0))
	assertEqual(0, Warp.brightness(1))
	assertNear(Warp.MAX_BRIGHTNESS, Warp.brightness(0.5), 1e-9)
	assert(Warp.brightness(0.25) < Warp.brightness(0.5), "rises to the middle")
	assert(Warp.brightness(0.75) < Warp.brightness(0.5), "falls after the middle")
end)
